Use active socket
membraneframework/membrane_tcp_plugin pull request #6
Opened 2024-04-24 11:19 UTC by Noarkhh

This PR modifies the Source so that it relies on a `:gen_tcp` socket using active mode rather than non-active, since the latter seems to use a lot more CPU in our implmentation, especially where the demand is higher than supply. To keep the flow control features the socket is using the `active: :once` or `active: N`, which limits the amount of messages that the element will receive before returning to `active: false` state.

2024-04-26 12:06 UTC, mat-hek requested changes

2024-04-26 12:06 UTC, mat-hek commented on lib/membrane_tcp/source.ex
> +                a process currently controlling the socket)
I recall we talked about spawning another process to simplify passing the control. It could look like this:
- The process that owns the socket calls `Membrane.TCP.Socket.new(local_socket)` which spawns a process that takes control and returns a wrapper containing the pid of the process
- The created wrapper is passed around wherever needed
- The wrapper is passed to `Membrane.TCP.Source` which calls `Membrane.TCP.Socket.get(self())` and the wrapper gives control to the TCP source

So the only thing the user would do is to call `Membrane.TCP.Socket.new` and then pass it to the element

2024-04-26 12:06 UTC, mat-hek commented on lib/membrane_tcp/source.ex
> +    :inet.setopts(state.local_socket.socket_handle, active: size)
This makes sense if only if the demand unit is buffers, you can enforce it in `def_output_pad`

2024-04-26 12:06 UTC, mat-hek commented on lib/membrane_tcp/source.ex
> +      [buffer: {:output, %Buffer{payload: payload, metadata: metadata}}, redemand: :output],
since we request the same amount of buffers from TCP that is demanded, the redemand is not needed

2024-05-06 13:09 UTC, Noarkhh commented on lib/membrane_tcp/source.ex
> +                a process currently controlling the socket)
There is a problem, this approach would require the process initially owning the socket (in our case the RTSP session) to depend on membrane_tcp_plugin to create the wrapper process.

2024-05-10 08:30 UTC, mat-hek approved these changes

2024-05-14 10:38 UTC, merged